/// using this is usefull when creating unit test 
/// because we put senarios for the test


//// create Promise that already resolved
// const p =Promise.resolve({id:1});
// p.then(result => console.log(result));



///// Create Promise that already rejected
// const p =Promise.reject(new Error('reason for rejection....'));
// p.catch(err => console.log(err.message));






